/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array_shift;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void testArrayShift(){
        int[] input1 = {1,2,4,5};
        int[] expectedOutput1 = {1,2,3,4,5};
        int[] input2 = {0,0,0,0,0};
        int[] expectedOutput2 = {0,0,0,1,0,0};;
        int[] input3 = {};
        int[] expectedOutput3 = {-60};

        assertArrayEquals(expectedOutput1, insertShiftArray(input1));
        assertArrayEquals(expectedOutput2, insertShiftArray(input2));
        assertArrayEquals(expectedOutput3, insertShiftArray(input3));
    }
}
