package testBikeLock;    /*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static bikeLock.bikeLock.bikeLock;
import static org.junit.Assert.assertEquals;

public class testBikeLock {
    @Test
    public void testBikeLock() {
        int expected1 = 12;
        int expected2 = 5;
        int expected3 = 0;

        int[] startPositions1 = new int[]{1, 5, 6, 8};
        int[] startPositions2 = new int[]{1, 2, 0, 8};
        int[] startPositions3 = new int[]{0, 0, 0, 0};

        assertEquals(expected1, bikeLock(startPositions1));
        assertEquals(expected2, bikeLock(startPositions2));
        assertEquals(expected3, bikeLock(startPositions3));
    }
}


