/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binarySearch;

import org.junit.Test;

import static binarySearch.App.binarySearch;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testBinarySearch(){
        int[] testArray1 = {1, 2, 3, 4, 5};
        int[] testArray2 = {10, -30, 44, 0};
        //expected
        assertEquals(2, binarySearch(3, testArray1));
        assertEquals(1, binarySearch(-30, testArray2));
        //failures
        int[] failArray = {1, 2, 3, 4, 5};
        assertEquals(-1, binarySearch(30, failArray));
        //edge
        int[] edgeArray = {0, 0, 0, 0, 14};
        assertEquals(0, binarySearch(0, edgeArray));
    }
}
